# Site settings
title: spain.opendataday.org
email: okfn@okfn.es
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spain.opendataday.org" # the base hostname & protocol for your site

twitter_username: okfn_spain
github_username: okfn-spain

# Build settings
markdown: kramdown
